### ISSUE TITLE
map.snps.to.genes:  Error in strsplit(first_line, "\t") : non-character argument

### ISSUE THREAD

**Issue by Lei-Guo** [neurogenomics/MAGMA_Celltyping#91] opened 2021-12-28 21:15 UTC
GWAS data were formatted by format_sumstats first and were then passed to map.snps.to.genes.

datasets <- MungeSumstats::import_sumstats(ids = "ieu-a-298", save_dir = getwd(), download_method = "axel", nThread = 8)
datasets_fmt <- format_sumstats(path=datasets[[1]], nThread = 8, save_path = "ieu-a-298_fmt.tsv.gz")
datasets_fmt_gene <- map.snps.to.genes(path_formatted='ieu-a-298_fmt.tsv.gz')

Reading header.
Error in strsplit(first_line, "\t") : non-character argument

**Comment by Al-Murphy** [comment] 2021-12-28 22:33
Hey!

I would try reading in the formatted dataset `datasets_fmt`, I think the issue is likely there. Could you send the outputted print messages from format_sumstats call too?

Thanks

**Comment by Al-Murphy** [comment] 2021-12-28 22:43
Check that the following gives you the same result, I ran your code and can read in the reformatted dataset:

```
data.table::fread(datasets_fmt)
              SNP CHR       BP A1 A2 INFO    BETA     SE      LP     N         ID            P
    1: rs76805690   1  2256288  C  A    1  0.0389 0.0175 1.58536 74046 rs76805690 0.0259800510
    2: rs75379543   1  2261983  C  A    1  0.0427 0.0167 1.96738 74046 rs75379543 0.0107800308
    3: rs75273719   1  2263666  G  A    1  0.0502 0.0171 2.47353 74046 rs75273719 0.0033610115
    4:   rs903904   1  2263888  C  T    1  0.0413 0.0169 1.82769 74046   rs903904 0.0148699668
    5: rs80107522   1  2265070  T  C    1  0.0446 0.0168 2.11328 74046 rs80107522 0.0077040661
   ---                                                                                        
10081:  rs6008402  22 48209939  G  A    1 -0.0538 0.0153 3.35242 74046  rs6008402 0.0004442015
10082: rs74876332  22 48210968  T  C    1 -0.0538 0.0151 3.42377 74046 rs74876332 0.0003769034
10083: rs11090825  22 48682578  A  G    1  0.0916 0.0276 3.03934 74046 rs11090825 0.0009133979
10084: rs73169417  22 48684220  A  C    1  0.0302 0.0162 1.20259 74046 rs73169417 0.0627205705
10085:  rs9628575  22 49215182  A  C    1 -0.0427 0.0173 1.86582 74046  rs9628575 0.0136200907
```

**Comment by Lei-Guo** [comment] 2021-12-28 22:44
datasets_fmt <- format_sumstats(path=datasets[[1]],ref_genome ="GRCh37", nThread = 8, save_path = "ieu-a-298_fmt.tsv.gz
Reading header.
Tabular format detected.
Importing tabular file: ieu-a-298.tsv.gz
Standardising column headers.
First line of summary statistics file:
SNP	CHR	BP	A1	A2	INFO	BETA	SE	LP	N	ID	P
Summary statistics report:
   - 10,085 rows
   - 10,085 unique variants
   - 478 genome-wide significant variants (P<5e-8)
   - 22 chromosomes
Checking for multi-GWAS.
Checking for multiple RSIDs on one row.
Checking SNP RSIDs.
Checking for merged allele column.
Ensuring all SNPs are on the reference genome.
Loading reference genome data.
Checking for correct direction of A1 (reference) and A2 (alternative allele).
Checking for missing data.
Checking for duplicate columns.
Checking for duplicate SNPs from SNP ID.
Checking for SNPs with duplicated base-pair positions.
Filtering SNPs based on INFO score.
Filtering SNPs, ensuring SE>0.
Ensuring all SNPs have N<5 std dev above mean.
Removing 'chr' prefix from CHR.
Making X/Y CHR uppercase.
Checking for bi-allelic SNPs.
N already exists within sumstats_dt.
Sorting coordinates.
Writing in tabular format ==> ieu-a-298_fmt.tsv.gz
Summary statistics report:
   - 10,085 rows (100% of original 10,085 rows)
   - 10,085 unique variants
   - 478 genome-wide significant variants (P<5e-8)
   - 22 chromosomes
Successfully finished preparing sumstats file, preview:
Reading header.
          SNP CHR      BP A1 A2 INFO   BETA     SE      LP     N         ID
1: rs76805690   1 2256288  C  A    1 0.0389 0.0175 1.58536 74046 rs76805690
2: rs75379543   1 2261983  C  A    1 0.0427 0.0167 1.96738 74046 rs75379543
3: rs75273719   1 2263666  G  A    1 0.0502 0.0171 2.47353 74046 rs75273719
4:   rs903904   1 2263888  C  T    1 0.0413 0.0169 1.82769 74046   rs903904
             P
1: 0.025980051
2: 0.010780031
3: 0.003361012
4: 0.014869967
Returning path to saved data.

**Comment by Lei-Guo** [comment] 2021-12-28 22:46
Thank you for your prompt reply. The datasets_fmt seem to be same but map.snps.to.genes gives me the same error.

**Comment by Lei-Guo** [comment] 2021-12-28 22:59
looks like the error is from the following line, which returns a data.table/frame instead of a string:

MungeSumstats:::read_header(path = path_formatted, n = 1)

**Comment by Al-Murphy** [comment] 2021-12-28 23:14
Yep I get the same issue with the main branch, @bschilder any thought on how this bug happened? It may be a little while before I am able to push a fix (I want to make sure there isn't an underlying reason this is happening - Brain it would be good to get your input too) but I think if you just force the read_header() return to a string on your cloned branch it should cover you for this:

```
first_line <- as.character(MungeSumstats:::read_header(path = 'ieu-a-298_fmt.tsv.gz', n = 1))
```

**Comment by bschilder** [comment] 2022-01-04 13:03
I believe I corrected this bug in my dev version. @Lei-Guo you can install the dev version with:

```R
remotes::install_github("neurogenomics/MAGMA_Celltyping@bschilder_dev")
```
Note that `map.snps.to.genes` is now `map_snps_to_genes` in this dev version. 

Working out the last of the kinks and then will hopefully merge with the main soon.

**Comment by Al-Murphy** [comment] 2022-01-04 17:02
@Lei-Guo I've pushed a fix for this to the master branch

**Closed as completed by Al-Murphy** 2022-01-04 17:02 UTC
