### ISSUE TITLE
Issue downloading & unzipping reference files for MAGMA run

### ISSUE THREAD

**Issue by Al-Murphy** [neurogenomics/MAGMA_Celltyping#154] opened 2024-10-02 17:56 UTC
## 1. Bug description

Seems to be an issue downloading the reference files for MAGMA - specifically here my issue is with g1000_eur.bed. It fails on the example code from the vignette. Worth noting the cached folder is empty (`/Users/alanmurphy/Library/Caches/org.R-project.R/R/MAGMA.Celltyping/g1000_eur/`) where the file **should** download. I managed to download it myself manually (`wget https://ctg.cncr.nl/software/MAGMA/ref_data/g1000_eur.zip`) as a zip file (~130kb size) but then the unzipping produced strange errors.

### Console output 

Short error output:

```
ERROR - parsing arguments: file '/Users/alanmurphy/Library/Caches/org.R-project.R/R/MAGMA.Celltyping/g1000_eur/g1000_eur.bed' specified in --bfile does not exist or is not a file.

Terminating program.
Warning messages:
1: In utils::unzip(zipfile = zipfile, exdir = genome_ref_dir, overwrite = TRUE) :
  error 1 in extracting from zip file
2: In file.remove(zipfile, showWarnings = FALSE) :
  cannot remove file 'FALSE', reason 'No such file or directory'
```

Full output:

<details>

```
> path_formatted <- MAGMA.Celltyping::get_example_gwas(
+   trait = "prospective_memory")
Importing munged GWAS summary statistics: prospective_memory
ℹ Downloading "prospective_memory.ukb.tsv.gz"...
  |======================================================================================================================================================| 100%
Saving decompressed copy of path_formatted ==>  /var/folders/hd/jm8lzp7s4dl_wlkykzhz66x80000gn/T//RtmpWR0d37/prospective_memory.ukb.tsv
> genesOutPath <- MAGMA.Celltyping::map_snps_to_genes(
+   path_formatted = path_formatted,
+   genome_build = "GRCh37")
Installed MAGMA version: v1.10
Skipping MAGMA installation.
The desired_version of MAGMA is currently installed: v1.10
Using: magma_v1.10_mac
genome_ref not found in storage_dir. Downloading from remote server instead ==> /Users/alanmurphy/Library/Caches/org.R-project.R/R/MAGMA.Celltyping/g1000_eur
trying URL 'https://ctg.cncr.nl/software/MAGMA/ref_data/g1000_eur.zip'
Error in utils::download.file(url = input_url, destfile = zipfile) : 
  cannot open URL 'https://ctg.cncr.nl/software/MAGMA/ref_data/g1000_eur.zip'
In addition: Warning message:
In utils::download.file(url = input_url, destfile = zipfile) :
  URL 'https://ctg.cncr.nl/software/MAGMA/ref_data/g1000_eur.zip': status was 'Couldn't resolve host name'
> genesOutPath <- MAGMA.Celltyping::map_snps_to_genes(
+   path_formatted = path_formatted,
+   genome_build = "GRCh37")
Installed MAGMA version: v1.10
Skipping MAGMA installation.
The desired_version of MAGMA is currently installed: v1.10
Using: magma_v1.10_mac
genome_ref not found in storage_dir. Downloading from remote server instead ==> /Users/alanmurphy/Library/Caches/org.R-project.R/R/MAGMA.Celltyping/g1000_eur
trying URL 'https://ctg.cncr.nl/software/MAGMA/ref_data/g1000_eur.zip'
Content type 'text/html; charset=UTF-8' length 130070 bytes (127 KB)
==================================================
downloaded 127 KB

Unzipping file.
ℹ All local files already up-to-date!

==== MAGMA Step 1: Generate genes.annot file ====

Welcome to MAGMA v1.10 (custom)
Using flags:
	--annotate window=35,10
	--snp-loc /var/folders/hd/jm8lzp7s4dl_wlkykzhz66x80000gn/T/RtmpWR0d37/prospective_memory.ukb.tsv
	--gene-loc /Users/alanmurphy/Library/Caches/org.R-project.R/R/MAGMA.Celltyping/NCBI37.3.gene.loc
	--out /var/folders/hd/jm8lzp7s4dl_wlkykzhz66x80000gn/T/RtmpWR0d37/MAGMA_Files/prospective_memory.ukb.tsv.35UP.10DOWN/prospective_memory.ukb.tsv.35UP.10DOWN

Start time is 18:45:49, Wednesday 02 Oct 2024

Starting annotation...
Reading gene locations from file /Users/alanmurphy/Library/Caches/org.R-project.R/R/MAGMA.Celltyping/NCBI37.3.gene.loc... 
	adding window: 35000bp (before), 10000bp (after)
	19161 gene locations read from file
	chromosome  1: 2016 genes
	chromosome  2: 1226 genes
	chromosome  3: 1050 genes
	chromosome  4: 745 genes
	chromosome  5: 856 genes
	chromosome  6: 750 genes
	chromosome  7: 906 genes
	chromosome  8: 669 genes
	chromosome  9: 775 genes
	chromosome 10: 723 genes
	chromosome 11: 1275 genes
	chromosome 12: 1009 genes
	chromosome 13: 320 genes
	chromosome 14: 595 genes
	chromosome 15: 586 genes
	chromosome 16: 817 genes
	chromosome 17: 1147 genes
	chromosome 18: 271 genes
	chromosome 19: 1389 genes
	chromosome 20: 527 genes
	chromosome 21: 215 genes
	chromosome 22: 442 genes
	chromosome  X: 805 genes
	chromosome  Y: 47 genes
Reading SNP locations from file /var/folders/hd/jm8lzp7s4dl_wlkykzhz66x80000gn/T/RtmpWR0d37/prospective_memory.ukb.tsv... 
	WARNING: on line 1, chromosome code 'CHR' not recognised; skipping SNP (ID = SNP)
	398092 SNP locations read from file                                                             
	of those, 215415 (54.11%) mapped to at least one gene
Writing annotation to file /var/folders/hd/jm8lzp7s4dl_wlkykzhz66x80000gn/T/RtmpWR0d37/MAGMA_Files/prospective_memory.ukb.tsv.35UP.10DOWN/prospective_memory.ukb.tsv.35UP.10DOWN.genes.annot
	for chromosome  1, 744 genes are empty (out of 2016)
	for chromosome  2, 425 genes are empty (out of 1226)
	for chromosome  3, 319 genes are empty (out of 1050)
	for chromosome  4, 275 genes are empty (out of 745)
	for chromosome  5, 252 genes are empty (out of 856)
	for chromosome  6, 234 genes are empty (out of 750)
	for chromosome  7, 275 genes are empty (out of 906)
	for chromosome  8, 272 genes are empty (out of 669)
	for chromosome  9, 238 genes are empty (out of 775)
	for chromosome 10, 239 genes are empty (out of 723)
	for chromosome 11, 394 genes are empty (out of 1275)
	for chromosome 12, 313 genes are empty (out of 1009)
	for chromosome 13, 121 genes are empty (out of 320)
	for chromosome 14, 211 genes are empty (out of 595)
	for chromosome 15, 220 genes are empty (out of 586)
	for chromosome 16, 307 genes are empty (out of 817)
	for chromosome 17, 305 genes are empty (out of 1147)
	for chromosome 18, 84 genes are empty (out of 271)
	for chromosome 19, 393 genes are empty (out of 1389)
	for chromosome 20, 151 genes are empty (out of 527)
	for chromosome 21, 65 genes are empty (out of 215)
	for chromosome 22, 150 genes are empty (out of 442)
	for chromosome  X, 805 genes are empty (out of 805)
	for chromosome  Y, 47 genes are empty (out of 47)
	at least one SNP mapped to each of a total of 12322 genes (out of 19161)


End time is 18:45:50, Wednesday 02 Oct 2024 (elapsed: 00:00:01)

==== MAGMA Step 2: Generate genes.out ====

Welcome to MAGMA v1.10 (custom)
Using flags:
	--bfile /Users/alanmurphy/Library/Caches/org.R-project.R/R/MAGMA.Celltyping/g1000_eur/g1000_eur synonym-dup=skip
	--pval /var/folders/hd/jm8lzp7s4dl_wlkykzhz66x80000gn/T/RtmpWR0d37/prospective_memory.ukb.tsv ncol=N duplicate=drop
	--gene-annot /var/folders/hd/jm8lzp7s4dl_wlkykzhz66x80000gn/T/RtmpWR0d37/MAGMA_Files/prospective_memory.ukb.tsv.35UP.10DOWN/prospective_memory.ukb.tsv.35UP.10DOWN.genes.annot
	--out /var/folders/hd/jm8lzp7s4dl_wlkykzhz66x80000gn/T/RtmpWR0d37/MAGMA_Files/prospective_memory.ukb.tsv.35UP.10DOWN/prospective_memory.ukb.tsv.35UP.10DOWN

Start time is 18:45:50, Wednesday 02 Oct 2024


ERROR - parsing arguments: file '/Users/alanmurphy/Library/Caches/org.R-project.R/R/MAGMA.Celltyping/g1000_eur/g1000_eur.bed' specified in --bfile does not exist or is not a file.

Terminating program.
Warning messages:
1: In utils::unzip(zipfile = zipfile, exdir = genome_ref_dir, overwrite = TRUE) :
  error 1 in extracting from zip file
2: In file.remove(zipfile, showWarnings = FALSE) :
  cannot remove file 'FALSE', reason 'No such file or directory'
```

</details>

### Code 

```R
path_formatted <- MAGMA.Celltyping::get_example_gwas(
  trait = "prospective_memory")

genesOutPath <- MAGMA.Celltyping::map_snps_to_genes(
  path_formatted = path_formatted,
  genome_build = "GRCh37")
```

## 3. Session info

MAGMA.Celltyping v2.0.12, MAGMA v1.10. All packages:

<details>

```
R version 4.3.0 (2023-04-21)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS 14.3.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Dublin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] MAGMA.Celltyping_2.0.12

loaded via a namespace (and not attached):
  [1] fs_1.6.4                      matrixStats_1.4.1             bitops_1.0-8                  lubridate_1.9.3               httr_1.4.7                   
  [6] RColorBrewer_1.1-3            doParallel_1.0.17             gh_1.4.1                      tools_4.3.0                   backports_1.5.0              
 [11] utf8_1.2.4                    R6_2.5.1                      lazyeval_0.2.2                GetoptLong_1.0.5              prettyunits_1.2.0            
 [16] cli_3.6.3                     Biobase_2.62.0                ewceData_1.10.0               Rsamtools_2.18.0              yulab.utils_0.1.7            
 [21] R.utils_2.12.3                dichromat_2.0-0.1             BSgenome_1.70.2               orthogene_1.9.1               maps_3.4.2                   
 [26] limma_3.58.1                  rstudioapi_0.16.0             RSQLite_2.3.7                 pals_1.9                      generics_0.1.3               
 [31] gridGraphics_0.5-1            shape_1.4.6.1                 BiocIO_1.12.0                 gtools_3.9.5                  car_3.1-3                    
 [36] dplyr_1.1.4                   homologene_1.4.68.19.3.27     Matrix_1.6-5                  fansi_1.0.6                   S4Vectors_0.40.2             
 [41] abind_1.4-8                   R.methodsS3_1.8.2             lifecycle_1.0.4               scatterplot3d_0.3-44          yaml_2.3.10                  
 [46] carData_3.0-5                 SummarizedExperiment_1.32.0   gplots_3.1.3.1                SparseArray_1.2.4             BiocFileCache_2.10.2         
 [51] grid_4.3.0                    blob_1.2.4                    promises_1.3.0                ExperimentHub_2.10.0          crayon_1.5.3                 
 [56] lattice_0.22-6                GenomicFeatures_1.54.4        KEGGREST_1.42.0               mapproj_1.2.11                MungeSumstats_1.10.1         
 [61] knitr_1.48                    pillar_1.9.0                  ComplexHeatmap_2.18.0         KGExplorer_0.99.03            GenomicRanges_1.54.1         
 [66] rjson_0.2.23                  boot_1.3-30                   codetools_0.2-20              glue_1.8.0                    ggfun_0.1.6                  
 [71] data.table_1.16.0             vctrs_0.6.5                   png_0.1-8                     treeio_1.26.0                 gtable_0.3.5                 
 [76] assertthat_0.2.1              HPOExplorer_1.0.3             cachem_1.1.0                  xfun_0.47                     S4Arrays_1.2.1               
 [81] mime_0.12                     tidygraph_1.3.1               gargle_1.5.2                  SingleCellExperiment_1.24.0   RNOmni_1.0.1.2               
 [86] iterators_1.0.14              simona_1.0.10                 statmod_1.5.0                 interactiveDisplayBase_1.40.0 nlme_3.1-164                 
 [91] ggtree_3.10.1                 EWCE_1.13.1                   bit64_4.5.2                   progress_1.2.3                filelock_1.0.3               
 [96] googleAuthR_2.0.2             GenomeInfoDb_1.38.8           KernSmooth_2.23-22            splitstackshape_1.4.8         colorspace_2.1-1             
[101] BiocGenerics_0.48.1           DBI_1.2.3                     tidyselect_1.2.1              bit_4.5.0                     compiler_4.3.0               
[106] curl_5.2.3                    rvest_1.0.4                   httr2_1.0.5                   xml2_1.3.6                    ggdendro_0.2.0               
[111] DelayedArray_0.28.0           plotly_4.10.4                 rtracklayer_1.62.0            scales_1.3.0                  caTools_1.18.3               
[116] rappdirs_0.3.3                stringr_1.5.1                 digest_0.6.37                 piggyback_0.1.5               minqa_1.2.8                  
[121] rmarkdown_2.28                XVector_0.42.0                htmltools_0.5.8.1             pkgconfig_2.0.3               lme4_1.1-35.5                
[126] GeneOverlap_1.38.0            MatrixGenerics_1.14.0         dbplyr_2.5.0                  fastmap_1.2.0                 rlang_1.1.4                  
[131] GlobalOptions_0.1.2           htmlwidgets_1.6.4             shiny_1.9.1                   farver_2.1.2                  jsonlite_1.8.9               
[136] BiocParallel_1.36.0           R.oo_1.26.0                   VariantAnnotation_1.48.1      RCurl_1.98-1.16               magrittr_2.0.3               
[141] Formula_1.2-5                 GenomeInfoDbData_1.2.11       ggplotify_0.1.2               patchwork_1.3.0               munsell_0.5.1                
[146] Rcpp_1.0.13                   ape_5.8                       babelgene_22.9                stringi_1.8.4                 zlibbioc_1.48.2              
[151] MASS_7.3-60                   AnnotationHub_3.10.1          plyr_1.8.9                    parallel_4.3.0                Biostrings_2.70.3            
[156] splines_4.3.0                 hms_1.1.3                     circlize_0.4.16               igraph_2.0.3                  ggpubr_0.6.0                 
[161] ggsignif_0.6.4                reshape2_1.4.4                biomaRt_2.58.2                stats4_4.3.0                  gprofiler2_0.2.3             
[166] BiocVersion_3.18.1            XML_3.99-0.17                 evaluate_1.0.0                BiocManager_1.30.25           nloptr_2.1.1                 
[171] foreach_1.5.2                 httpuv_1.6.15                 rols_2.30.2                   grr_0.9.5                     tidyr_1.3.1                  
[176] purrr_1.0.2                   clue_0.3-65                   ggplot2_3.5.1                 broom_1.0.7                   xtable_1.8-4                 
[181] restfulr_0.0.15               gitcreds_0.1.2                tidytree_0.4.6                rstatix_0.7.2                 later_1.3.2                  
[186] viridisLite_0.4.2             MSTExplorer_1.0.4             Polychrome_1.5.1              tibble_3.2.1                  aplot_0.2.3                  
[191] memoise_2.0.1                 AnnotationDbi_1.64.1          GenomicAlignments_1.38.2      IRanges_2.36.0                cluster_2.1.6                
[196] HGNChelper_0.8.14             timechange_0.3.0  
```
</details>

**Comment by bschilder** [comment] 2024-10-02 18:00
I've confirmed that this is because the MAGMA team completely changed how they distribute resource files.
I fixed this for getting the MAGMA executables, but it seems the same issue is occurring for the genome refs.

While I'm working on fixing this, you can download the refs from their website directly, unzip it, and specify the `genome_ref_path` as its location.

See here under the **Reference Data** section
https://cncr.nl/research/magma/

**Comment by bschilder** [comment] 2024-10-02 18:50
@Al-Murphy I just pushed a fix for this, let me know if you have any more issues.

**Comment by Al-Murphy** [comment] 2024-10-02 19:59
Working for me now thank you!! I'll reopen if anything crops up! Really appreciate it Brian!

**Closed as completed** 2024-10-02 19:59 UTC
Labels: bug
