### ISSUE TITLE
Problem with get_genomeLocFile 

### ISSUE THREAD

**Issue by malosreet** [neurogenomics/MAGMA_Celltyping#101] opened 2022-02-10 18:47 UTC
Hello! 

I am just starting to use MAGMA.Celltyping and not familiar with GWAS related analysis. I am running into an error with map_snps_to_genes.

First I used import_sumstats from MungeSumstats to download the properly formatted GWAS summary statistics for several studies on Open GWAS. Then I am trying to use map_snps_to_genes, but I get the following error message on Step 1 of the MAGMA analysis. 

```
ERROR - reading gene location file: too few values on line 1:

        line: {
```

When I look at the "NCBI37.3.gene.loc" file this is what I see:

```
{
  
  "message": "Bad credentials",
  
  "documentation_url": "https://docs.github.com/rest"
  
}
```

I think this is happening because map_snps_to_genes is calling get_genomeLocFile, which calls get_data, which calls pb_download to try to get the appropriate files from the MAGMA.Celltyping respository. But the authentication fails so the download fails. 

Perhaps I can change something simple in my set-up to fix this problem. I downloaded the required file directly from the MAGMA website, but I couldn't figure out how to specify to map_snps_to_genes that it should use that file. 

Any advice is appreciated!

Malosree

**Comment by bschilder** [comment] 2022-02-10 20:09
i think this is a duplicate of #100

**Closed as completed by bschilder** 2022-02-10 20:09 UTC
